{
 "title": "oke",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "status",
    "label": "HTTP Status",
    "query": {
     "query": "label_values(user_service_http_requests_total{status_code=\"$status\"},code)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "metrics(.*_http_requests_total)"
    }
   },
   { "name": "instance", "label": "instance", "query": "${service}" }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(${service}_http_request_duration_seconds_bucket[5m])\n  )\n) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory thực tế",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${service}_process_resident_memory_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tổng xử lý CPU của người dùng và hệ thống",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "${service}_process_cpu_seconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Status (Up/Down)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"${instance}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tổng số request đã xử lý",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "${service}_http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Số request mỗi phút",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(${service}_http_requests_total[5m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tỉ lệ phần trăm lỗi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(${service}_http_requests_total{status_code=~\"4..|5..\"}[5m]))\n/\nsum(rate(${service}_http_requests_total[5m]))\n",
     "legendFormat": "Error Rate %"
    }
   ]
  }
 ]
}