FROM node:20-alpine

WORKDIR /app/drone-service

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN npx prisma generate

RUN pnpm run build

EXPOSE 3008

CMD [ "node", "dist/server.js" ]

