{
 "title": "Kafka - Topics",
 "tags": [
  "kafka",
  "topics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Topic overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic overview",
   "type": "table",
   "gridPos": { "x": 0, "y": 1, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic bytes in",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesinpersec[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic bytes out",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 17, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_bytesoutpersec[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Consumer group overview",
   "type": "table",
   "gridPos": { "x": 0, "y": 26, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "kafka_consumergroup_current_offset"
    }
   ]
  },
  {
   "title": "Consumer group consume rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 34, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 34, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}